### ISSUE TITLE
UpSampling2D vs UnPooling2D

### ISSUE THREAD

**Issue by pianomanu** [pradyu1993/segnet#10]
Hey, thanks for the example! 

I found the code on your blog post first and there you're using the custom layer ```UnPooling2D``` but here you define it as well but then use the build-in ```UpSampling2D```. 

Do they perform exactly the same operation? Why did you change? 
I understand the code for ```UnPooling2D``` but I'm a little bit confused by the code of ```UpSampling2D```..

Thanks in advance

**Comment by pradyu1993** [comment]
Hey @pianomanu, at the time I was coding Keras UpSampling2D layer was buggy so I wrote my own layer, later when the bug was fixed I changed the code to use UpSampling2D layer.

**Comment by pianomanu** [comment]
Thanks for the quick answer :) 
I'll use UpSampling2D then!
