### ISSUE TITLE
Regarding migrating this implementation to Tensorflow-based 

### ISSUE THREAD

**Issue by huaiyanggongzi** [pradyu1993/segnet#5]
Hi Pradyumna,

Thanks for sharing the code. Just curious, how difficult(or different) if migrating this implementation to Tensorflow-based? Or what are the major parts need to be modified? I am not familiar with Keras, and am learning Tensorflow.

**Comment by ahundt** [comment]
keras can run a tensorflow backend or a theano backend, details on using each are on the website https://keras.io, sometimes there is a bit of work to switch between them but typically not too crazy.

**Comment by huaiyanggongzi** [comment]
Thanks!
