### ISSUE TITLE
Difference in output as shown in Segnet.ipynb

### ISSUE THREAD

**Issue by muaz-git** [pradyu1993/segnet#8]
Hello,

I am just trying to run your code, I just tried to run the same example as it is mentioned is Segnet.ipynb but unfortunately I am not able to generate the same results as it is shown in it. So this is the image 
![0001tp_006750](https://cloud.githubusercontent.com/assets/23000414/21853557/e7a9e6c8-d817-11e6-868c-f3ca044e2bb7.png)

what I tried to feed the network and this is the output I am getting.

![output](https://cloud.githubusercontent.com/assets/23000414/21853517/b1ea5554-d817-11e6-931b-bfec7fd1a451.png)

Can you please help me what I am doing wrong. 

Best,
Muaz

**Comment by pradyu1993** [comment]
@muaz-git you will have to train the network to get meaningful results. Let me know how it goes :)
